### ISSUE TITLE
[Add]

### ISSUE THREAD

**Issue by JusToastDEV** [The-GeyserMC-CumJars-Collection/The-GeyserMC-CumJars-Collection.github.io#11]
**JusToastYT**

**Nah, I just want to make epic additions**

**like a shitty mlg meme comp**

**Comment by E404NNF** [comment]
Holy fuck I forgot this existed

**Comment by JusToastDEV** [comment]
> Holy fuck I forgot this existed

lol

**Comment by Saraistupid** [comment]
I don't want to associate with Geyser anymore because of some personal reasons, sorry.
